version: '3.8'

services:

  names_detector:
    build: ./names_detector
    image: icr.io/${ICR_NAMESPACE}/names_detector:${SHORT_SHA}
    ports: 
    - "5000:5000" 
    networks:
      - net-main

  names_detector_2:
    build: ./names_detector_2
    image: icr.io/${ICR_NAMESPACE}/names_detector_2:${SHORT_SHA}
    ports:
    - "3000:3000"
    networks:
      - net-main  


networks:
  net-main:
    driver: bridge

volumes:
  database:
    driver: local
