CREATE TABLE names(Muslim_Male_baby_names_A_to_Z VARCHAR(10),Column_2 VARCHAR(50));
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Aaban','Name of the Angel.');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Aadil','Just, Upright. ');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Aafiya','Good Health. ');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Aahil','Prince. ');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Aalam','World.');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Aalee','Sublime, high.');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Aalim','Religious Scholar. ');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Aamil','Doer, Work man. ');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Aamir','Civilised. ');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Aamirah','Inhabitant');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Aaqib','Follower.');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Aaqil','Intelligent. ');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Aarif','Knowing, aware.');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Aariz','Respectable man.');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Aashif','Bold, courageous.');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Aashir','Living.');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Aasif','An able minister.');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Aasim','Person who keeps away from sins. ');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Aatif','Kind Affectionate. ');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Aazim','Determined. ');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Abaan','Old Arabic name');
INSERT INTO names (Muslim_Male_baby_names_A_to_Z,Column_2) VALUES ('Abbas','Gloomy look. ');