name: Building and Deploying to IBM cloud kubernetes

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

      
# Environment variables for all jobs and steps
env:
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_REGION: global
  ICR_NAMESPACE: ${{ secrets.ICR_NAMESPACE }}
  IKS_CLUSTER: cg4ve3hf06pqhslaqr4g
  GITHUB_SHA: ${{ github.sha }}

jobs:
  continous-intergration-deployment:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: SHORT_SHA from git_sha
      run: |
        echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
        apt-get install gettext-base
        envsubst < kubernetes\names-detector-deployment.yaml
        envsubst < kubernetes\names-detector-2-deployment.yaml


    - name: Installing and configuring IBM Cloud CLI
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
        ibmcloud plugin install -f kubernetes-service
        ibmcloud plugin install -f container-registry

    - name: Authentication with IBM Cloud
      continue-on-error: true
      run: |
        ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g default

    - name: Docker build and push
      run: |
         docker-compose build
         ibmcloud cr region-set "${IBM_CLOUD_REGION}"
         ibmcloud cr login
         docker push icr.io/$ICR_NAMESPACE/names_detector:$SHORT_SHA
         docker push icr.io/$ICR_NAMESPACE/names_detector_2:$SHORT_SHA

    - name: Deploying to kubernetes
      run: |
        ibmcloud ks cluster config --cluster $IKS_CLUSTER
        kubectl config current-context
        kubectl apply -f kubernetes
        kubectl get deployment
        kubectl get service

